<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popisek ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>
	</head>

<h1>Editor služeb</h1>


<form method="post">
    <input type="hidden" name="sluzba_id" value="<?= $sluzba['sluzba_id'] ?>" />
    Titulek<br />
    <input type="text" name="titulek" value="<?= $sluzba['titulek'] ?>" /><br />
    URL<br />
    <input type="text" name="url" value="<?= $sluzba['url'] ?>" /><br />
    Popisek<br />
    <input type="text" name="popisek" value="<?= $sluzba['popisek'] ?>" /><br />
    Klíčová slova<br />
    <input type="text" name="klicova_slova" value="<?= $sluzba['klicova_slova'] ?>" /><br />
    <textarea id="obsah" name="obsah"><?= $sluzba['obsah'] ?></textarea>
    <input type="submit" value="Uložit službu" />
</form>


<script src="/tinymce/tinymce.min.js"></script>
<script src="/tinymce/jquery.tinymce.min.js"></script>

<script type="text/javascript">
    // Nastavení použité pro TinyMCE 5.7.1
    tinymce.init({

        selector: '#obsah', // Altenativní zápis: `selector: 'textarea[name=obsah]'` nebo pouze `selector: 'textarea'`
        language: 'cs',
        toolbar_mode: 'sliding',

        // Doporučené, vypíná převod české diakritiky na entity, šetří místo v tabulce, chceme text formátovat do html tagů
        entities: '160,nbsp',
        entity_encoding: 'named',

        // Doporučené
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],

        // Doporučené
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    });
</script>

</html>