<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popisek ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>
	</head>

<h1>Editor uživatelů</h1>

<form method="post">
    <input type="hidden" name="uzivatele_id" value="<?= $uzivatel['uzivatele_id'] ?>">
    <br />
    Jméno:<br />
    <input type="text" name="jmeno" placeholder="Jméno" value="<?= $uzivatel['jmeno'] ?>"/><br />
    Příjmení:<br />
    <input type="text" name="prijmeni" placeholder="Příjmení" value="<?= $uzivatel['prijmeni'] ?>"/><br />
    Rodné číslo:<br />
    <input type="text" name="rodne_cislo" placeholder="0000001234" value="<?= $uzivatel['rodne_cislo'] ?>"/><br />
    Telefon:<br />
    <input type="text" name="telefon" placeholder="+420111222333" value="<?= $uzivatel['telefon'] ?>"/><br />
    Email:<br />
    <input type="text" name="email" placeholder="jmeno@email.xxx" value="<?= $uzivatel['email'] ?>"/><br />
    Adresa:<br />
    <input type="text" name="adresa" placeholder="ulice čp."value="<?= $uzivatel['adresa'] ?>"/><br />
    Město:<br />
    <input type="text" name="mesto" placeholder="město" value="<?= $uzivatel['mesto'] ?>"/><br />
    Služba:<br />
    <input type="text" name="kod_sluzby" placeholder="kód služby" value="<?= $uzivatel['kod_sluzby'] ?>"/><br />
    <input type="text" name="jmeno_sluzby" placeholder="jméno služby" value="<?= $uzivatel['jmeno_sluzby'] ?>"/><br />
    <textarea id="sluzba" name="sluzba"><?= $uzivatel['sluzba'] ?></textarea>
    <input type="submit" value="Uložit změny" />
</form>


<!-- Celé texty
	uzivatele_id 	jmeno 	prijmeni 	rodne_cislo 	telefon 	email 	adresa 	mesto 	kod_sluby 	jmeno_sluby 	heslo  -->

<script src="/tinymce/tinymce.min.js"></script>
<script src="/tinymce/jquery.tinymce.min.js"></script>

<script type="text/javascript">
    // Nastavení použité pro TinyMCE 5.7.1
    tinymce.init({

        selector: '#obsah', // Altenativní zápis: `selector: 'textarea[name=obsah]'` nebo pouze `selector: 'textarea'`
        language: 'cs',
        toolbar_mode: 'sliding',

        // Doporučené, vypíná převod české diakritiky na entity, šetří místo v tabulce, chceme text formátovat do html tagů
        entities: '160,nbsp',
        entity_encoding: 'named',

        // Doporučené
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],

        // Doporučené
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    });
</script>

</html>