<h1>Registrace</h1>

<form method="post">
    Jméno:<br />
    <input type="text" name="jmeno" placeholder="Jméno" /><br />
    Příjmení:<br />
    <input type="text" name="prijmeni" placeholder="Příjmení" /><br />
    Rodné číslo:<br />
    <input type="text" name="rodne_cislo" placeholder="0000001234" /><br />
    Telefon:<br />
    <input type="text" name="telefon" placeholder="+420111222333" /><br />
    Email:<br />
    <input type="text" name="email" placeholder="vas@email.xxx" /><br />
    Adresa:<br />
    <input type="text" name="adresa" placeholder="Ulice, č.p." /><br />
    Město:<br />
    <input type="text" name="mesto" placeholder="Město" /><br />
    Heslo<br />
    <input type="password" name="heslo" placeholder="Heslo" /><br />
    Heslo znovu<br />
    <input type="password" name="heslo_znovu" placeholder="Heslo znovu" /><br />
    Zadejte aktuální rok (antispam)<br />
    <input type="text" name="rok" /><br />
    <input type="submit" value="Registrovat" />
</form>



