<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popisek ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>
	</head>

	<body>
		<header>
			<h1>AQUA Pojišťovna</h1>
		</header>
			<?php foreach ($zpravy as $zprava) : ?>
				<p class="zprava"><?= $zprava ?></p>
			<?php endforeach ?>
		<nav>
			<ul>
				<li><a href="sluzba/uvod">Úvod</a></li>
				<li><a href="sluzba">Služby</a></li>
				<li><a href="kontakt">Kontakt</a></li>	
				<li><a href="prihlaseni">Přihlášení</a></li>	
				<li><a href="detailuzivatele">Detail uživatele</a></li>
				<!-- <li><a href="uzivatel">Uživatel</a></li> -->
				<!-- <li><a href="registrace">Registrace</a></li>	 -->
				<!-- <li><a href="editor">Editor služeb</a></li> -->
				<!-- <li><a href="administrace">Administrace</a></li> -->
				
			</ul>
		</nav>
		<br clear="both" />
		
		<article>
			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
		</article>
		
		<footer>
			<p>Závěrečný projekt pro
			<a href="http://www.ITnetwork.cz" target="_blank">ITnetwork.cz</a>.</p>
		</footer>
	</body>
</html>